[2023-10-17 07:52:40,994] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: currency_btc_rub_every_10_munutes.get_rate_from_api_task manual__2023-10-17T07:52:38.326627+00:00 [queued]>
[2023-10-17 07:52:41,011] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: currency_btc_rub_every_10_munutes.get_rate_from_api_task manual__2023-10-17T07:52:38.326627+00:00 [queued]>
[2023-10-17 07:52:41,012] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-10-17 07:52:41,013] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2023-10-17 07:52:41,014] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-10-17 07:52:41,033] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): get_rate_from_api_task> on 2023-10-17 07:52:38.326627+00:00
[2023-10-17 07:52:41,041] {standard_task_runner.py:52} INFO - Started process 711 to run task
[2023-10-17 07:52:41,046] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'currency_btc_rub_every_10_munutes', 'get_rate_from_api_task', 'manual__2023-10-17T07:52:38.326627+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/hello.py', '--cfg-path', '/tmp/tmpdcy7go8_', '--error-file', '/tmp/tmpv0kcuzp_']
[2023-10-17 07:52:41,050] {standard_task_runner.py:80} INFO - Job 45: Subtask get_rate_from_api_task
[2023-10-17 07:52:41,174] {task_command.py:371} INFO - Running <TaskInstance: currency_btc_rub_every_10_munutes.get_rate_from_api_task manual__2023-10-17T07:52:38.326627+00:00 [running]> on host 5ae209acedc4
[2023-10-17 07:52:41,312] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Andrey1309
AIRFLOW_CTX_DAG_ID=currency_btc_rub_every_10_munutes
AIRFLOW_CTX_TASK_ID=get_rate_from_api_task
AIRFLOW_CTX_EXECUTION_DATE=2023-10-17T07:52:38.326627+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-17T07:52:38.326627+00:00
[2023-10-17 07:52:41,319] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: get_rate_from_api() takes 0 positional arguments but 6 were given
[2023-10-17 07:52:41,337] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=currency_btc_rub_every_10_munutes, task_id=get_rate_from_api_task, execution_date=20231017T075238, start_date=20231017T075240, end_date=20231017T075241
[2023-10-17 07:52:41,359] {standard_task_runner.py:97} ERROR - Failed to execute job 45 for task get_rate_from_api_task (get_rate_from_api() takes 0 positional arguments but 6 were given; 711)
[2023-10-17 07:52:41,384] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-17 07:52:41,438] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
